### PR TITLE
WIP addtraces implementation

### PR DESCRIPTION
**Pull request by cstjean**
I tried implementing `addtraces` using `evaljs`. It looks OK to me, but maybe I'm just [waving bamboo sticks pretending to be an airplane controller](http://calteches.library.caltech.edu/51/2/CargoCult.htm), because I still don't get any points displayed. Can you see anything wrong? The input values and dictionaries look OK, and `evaljs` returns `nothing`. How do you debug this? With a javascript console? 

Also, I don't understand what `to_image` and `svg_obs` are supposed to do. I guess it's asking Plotly to render, and send the output back to Julia?

### CODE REVIEW

**Comment by cstjean** [comment]
I redid everything with `Observable` similar to how you did the other functions, and it works now. Current issues: 

- The figure is first displayed empty, then the points are added.
- The Plots.jl formatter isn't called (so eg. dates show up as numbers). That may be a problem in my Plots.jl backend code.

**Comment by sglyon** [comment]
That's great!

Will you please push the working version so I can take a look?

>The Plots.jl formatter isn't called (so eg. dates show up as numbers). That may be a problem in my Plots.jl backend code.

This is actually intended. The way it currently works (or at least should work) in Plots.jl with the plotlyjs backend is that you call `Plots.plot!`, which then applies the entire plots pipeline and eventually calls `PlotlyJS.addtraces!` after all formatting steps have been completed on the Plots.jl side. It should work similarly with this backend.

**Comment by cstjean** [comment]
Done.

**Comment by cstjean** [comment]
With this PR and Plots.jl, `plot([1,2]).o.p.data` is empty, which makes sense because I'm just calling the JS `addtraces`. `plotlyjs()` maintains the Julia-side state. Should we do the same with PlotlyWebIO? Does `plotlyjs()` maintain both the Julia `Plot()` state and the JS state updated at the same time? Why the redundancy?

If I'm understanding the parallels with PlotlyJS correctly, `WebIOPlot` is a bit like `SyncPlot`, right? 

Subplots don't work yet. I feel like I need to get this function right, but I don't even understand the purpose of the first branch of the `if`. Why does Plots.jl call `create_backend_figure` when it wants to overwrite the current figure?

```julia
function _create_backend_figure(plt::Plot{PlotlyWebIOBackend})
    if !isplotnull() && plt[:overwrite_figure] && isa(current().o, PlotlyWebIO.WebIOPlot)
        println("update_backend")
        # This is what plotlyjs.jl is doing:
        # PlotlyJS.SyncPlot(PlotlyJS.Plot(), current().o.view)
        # This makes some sense, but does not work:
        return PlotlyWebIO.WebIOPlot(PlotlyWebIO.Plot(),
                                     plt.o.scope,
                                     plt.o.svg,
                                     plt.o.api_obs,
                                     plt.o.event_functions,
                                     plt.o.event_data,
                                     plt.o.event_obs) 
        # This works for single plots, but doesn't feel right
        return PlotlyWebIO.WebIOPlot()
    else
        println("create_backend")
        return PlotlyWebIO.WebIOPlot()
    end
end
```

Another (related?) issue:

```julia
plotlywebio()
pl = plot(plot([1,2]), plot([3,4]));
display(pl.o.scope)
pl.o.p.layout.fields
```

shows

```julia
Dict{Symbol,Any} with 1 entry:
  :margin => Dict(:l=>50,:b=>50,:r=>50,:t=>60)
```

whereas with `plotlyjs()` I get a big dictionary with the full layout specified, but only if I `display(pl)` first. I'm guessing that a lot of information gets passed from `Plots.jl` to `PlotlyJS.jl` when the plot is displayed, and this is not happening with `plotlywebio` because I'm displaying with `display(pl.o.scope)`. 

EDIT: just noticed that subplots haven't been fully coded with regular PlotlyWebIO; probably need that first. They work with 

```julia
sc = PlotlyWebIO.scatter(x=[1,2], y=[2,3])
sc2 = PlotlyWebIO.scatter(x=[1,2], y=[6,3])
WebIOPlot([Plot(sc), Plot(sc2)]).scope
```

**Comment by sglyon** [comment]
> If I'm understanding the parallels with PlotlyJS correctly, WebIOPlot is a bit like SyncPlot, right?

Yes, this is correct. I see WebIOPlot as a prototype for the next-generation SyncPlot

> .... Should we do the same with PlotlyWebIO? Does plotlyjs() maintain both the Julia Plot() state and the JS state updated at the same time? Why the redundancy?

Yes PlotlyJS.jl (and the plotlyjs backend) keeps the displayed plot and Julia representation of the plot in sync (hence the name SyncPlot ;) ). This was a deliberate decision by me to ensure that any changes you make to the plot after it is displayed will be active both on the display and in Julia. One setting where this matters is when you want to edit a plot after display, then save the json spec to a file. The json spec is entirely generated from the Julia representation of the plot, so if that was out of sync with the display then your json wouldn't match.

In PlotlyJS.jl I define all the javascript api methods for the `PlotlyBase.Plot` type and for the `PlotlyJS.XXXDisplay` types (which sends the data to javascript). Then the implementation of these methods for SyncPlot is to just pass all arguments to the `PlotlyBase.Plot` and `PlotlyJS.XXXDisplay`. I feel I did a poor job explaining -- see [here](https://github.com/sglyon/PlotlyJS.jl/blob/4f0c99aed8a5993a08041d02cf4cd631908c4dbb/src/display.jl#L69-L75) for where that is implemented.

> Subplots don't work yet. I feel like I need to get this function right, but I don't even understand the purpose of the first branch of the if. Why does Plots.jl call create_backend_figure when it wants to overwrite the current figure?

I'm sorry but I don't think I'm the right one to answer Plots.jl internals questions. We could probably figure it out together, but I think it would be more efficient to ask one of the Plots.jl devs

> I'm guessing that a lot of information gets passed from Plots.jl to PlotlyJS.jl when the plot is displayed, and this is not happening with plotlywebio because I'm displaying with display(pl.o.scope)

That is correct! You will need to hook into the Plots.jl rendering pipeline like the plotlyjs backend does. 

> EDIT: just noticed that subplots haven't been fully coded with regular PlotlyWebIO; probably need that first. They work with

That is correct, though it would be only a few lines of code to add.

You would need to do what we did for SyncPlot [here](https://github.com/sglyon/PlotlyJS.jl/blob/c9b8abca957e9d84326c609ba3b9d2b001d1147a/src/util.jl#L6-L11)

**Comment by shashi** [comment]
With #6 I think this just reduces to:

```julia
function addtraces!(plt::WebIOPlot, traces::AbstractTrace...)
    send_command(plt, :addTraces, traces)
end
```
:smile:

**Pull request closed without merging**
