### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by shashi**
This includes a bunch of changes:

1. WebIOPlot now contains 2 fields: the `PlotlyBase.Plot` object and a `WebIO.Scope` object
2. `plot["hover"]` is forwarded to `plot.scope["hover"]`, this means you can now add handlers like this:
```
on(plot["hover"]) do event_data
  ... handle a hover event ...
end
```
or
```
# JS
onjs(plot["hover"], @js (event) -> ...)
```
If you want to directly handle raw [PlotlyJS events](https://plot.ly/javascript/plotlyjs-events/) you can pass an `events` kwarg (dict of event name to js function) which is forwarded to the plotDiv. (These events have to be named `plotly_hover` etc. with the prefix and all. This is JS-only!
3. Removes the need for event types by introducing a low-level `send_command`--`send_command(plot, :update, args...)` will call `Plotly.update(plotDiv, args...)` on the JS making writing update functions trivial. I've kept those that were already there, it should be easy to add more in plotly_events.jl
4. adds a `show` method to display the plot directly
5. uses absolute path to assets -- new development in WebIO

### CODE REVIEW

**Comment by sglyon** [comment]
This is _awesome_

Thank you very much. I think with this we are probably ready to completely replace the display mechanisms in PlotlyJS.jl with this. The one thing that I was waiting on was a clean jupyterlab story. What is the status with WebIO in jupyterlab?

If you don't mind I think I'll throw your examples/comments into the readme for how to hook into the events from both the Julia and javascript side

**Comment by shashi** [comment]
Nice!

You're welcome to use the examples for whatever you want. I haven't tried Jupyter lab in a bit but it should work if you follow the setup instructions for the lab extension in the readme. We can make it part of the default build as well.

I think there are a couple of not so major issues before I'd say WebIO is as uniquitously working as `show`....

1. https://github.com/JuliaGizmos/WebIO.jl/issues/139
2. https://github.com/JuliaGizmos/WebIO.jl/issues/58

**Comment by cstjean** [comment]
@shashi On WebIO v.0.1.10 (because of https://github.com/JuliaGizmos/WebIO.jl/issues/152), this PR breaks PlotlyWebIO on IJulia (no display). 

```julia
using PlotlyWebIO
sc = PlotlyWebIO.scatter(x=[1,2], y=[2,3])
wpl = PlotlyWebIO.WebIOPlot(sc)
wpl.scope
```

The guilty commit from this PR is e65004b91d274f12fa70b971a79a4d5aa8d032a4. Of course, this might be because PlotlyWebIO requires the latest WebIO...

**Comment by shashi** [comment]
You need to build WebIO after updating to the latest version.

**Comment by cstjean** [comment]
Right - sorry that I gave no news on this front. I'll try the suggestions soon. This system is running as an internal tool, so I have to wait for the right circumstances to test it.

**Comment by cstjean** [comment]
I tried again on WebIO 0.2.4 and master (after `Pkg.build("WebIO")`, restarting the notebook server and my computer), and I'm seeing the same issue. PlotlyWebIO 2ebc27ff (before this PR) works, but master doesn't.

```
Kernel: kernel_restarting (baefff72-8667-4ce2-be57-ae2396d68f0e)
kernel.js:103
plotly comm init
main.min.js:26:9
Kernel: kernel_created (baefff72-8667-4ce2-be57-ae2396d68f0e)
kernel.js:103
Starting WebSockets: ws://192.168.128.129:8897/api/kernels/baefff72-8667-4ce2-be57-ae2396d68f0e
kernel.js:459
Kernel: kernel_connected (baefff72-8667-4ce2-be57-ae2396d68f0e)
kernel.js:103
Kernel: kernel_starting (baefff72-8667-4ce2-be57-ae2396d68f0e)
kernel.js:103
Error: Fetch error: 404 Not Found
  Instantiating http://192.168.128.129:8897/home/cst-jean/.julia/v0.6/PlotlyWebIO/src/../assets/plotly-latest.min.js
  Loading /home/cst-jean/.julia/v0.6/PlotlyWebIO/src/../assets/plotly-latest.min.js
main.min.js:2609
A scope with id 'scope-a3947f1d-0232-4b50-a36e-4b16ca75ea29' already exists.
main.min.js:123:9
Error: Fetch error: 404 Not Found
  Instantiating http://192.168.128.129:8897/home/cst-jean/.julia/v0.6/PlotlyWebIO/src/../assets/plotly-latest.min.js
  Loading /home/cst-jean/.julia/v0.6/PlotlyWebIO/src/../assets/plotly-latest.min.js
main.min.js:2609
Kernel: kernel_ready (baefff72-8667-4ce2-be57-ae2396d68f0e)
kernel.js:103
Object { type: "scope", id: "scope-a3947f1d-0232-4b50-a36e-4b16ca75ea29", data: {…}, sendCallback: sendCallback(), dom: div.wio-scope, handlers: {…}, observables: {…}, promises: {…} }
main.min.js:3:8
TypeError: allscopes is undefined[Learn More]
```

**Comment by cstjean** [comment]
Aha, I had to build PlotlyWebIO to get it to download plotly-latest.min.js. All good!

**Comment by cstjean** [comment]
> I think there are a couple of not so major issues before I'd say WebIO is as uniquitously working as show....

One more: in IJulia, when I save to HTML, PlotlyWebIO plots don't show up in the HTML version. May be related to https://github.com/JuliaGizmos/WebIO.jl/issues/85

**Pull request merged**
